### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by lassoan** [DCBIA-OrthoLab/SlicerAutomatedDentalTools#27]
This extension looks very useful. Unfortunately I could not figure out how it is supposed to be used.

I've downloaded the Masks_Models.zip model, unzipped and loaded the CBCT dental surgery sample data set, selected "PreDentalSurgery" as "Select node".  and clicked "Run Prediction". UnERROR: Nothing happened.

Python console shows this error:

```
Traceback (most recent call last):
  File "C:/Users/andra/AppData/Local/NA-MIC/Slicer 5.2.1/NA-MIC/Extensions-31317/SlicerAutomatedDentalTools/lib/Slicer-5.2/qt-scripted-modules/AMASSS.py", line 630, in onPredictButton
    if os.path.isfile(self.input_path):
  File "C:\Users/andra/AppData/Local/NA-MIC/Slicer 5.2.1/bin/../lib/Python/Lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by lassoan** [comment]
Opening the Save dialog (Ctrl-S) seems to have fixed the issue. Probably the code uses the storage node to export the input to file.

Storage node does not always exist (for example, no storage node exists if a sample data set is loaded). You could add a default storage node, but it would be probably better to use the export node feature (to avoid changing and restoring storage node properties).

Unfortunately, there is still no output.

This is the output in the Python console:

```
C:/Users/andra/OneDrive/Documents/PostDentalSurgery.nrrd
C:/Users/andra/OneDrive/Documents\Slicer_temp_AMASSS
parameters :  {'inputVolume': 'C:/Users/andra/OneDrive/Documents/PostDentalSurgery.nrrd', 'modelDirectory': 'C:/tmp/20221226-CMF-Seg', 'highDefinition': False, 'skullStructure': 'MAND MAX CB CV UAW SKIN CBMASK MANDMASK MAXMASK', 'merge': 'MERGE', 'genVtk': False, 'save_in_folder': False, 'output_folder': 'C:/Users/andra/OneDrive/Documents/PostDentalSurgery.nrrd', 'precision': 50, 'vtk_smooth': 5, 'prediction_ID': 'Pred', 'gpu_usage': 1, 'cpu_usage': 1, 'temp_fold': 'C:/Users/andra/OneDrive/Documents\\Slicer_temp_AMASSS'}
PROCESS DONE.
AMASSS_CLI standard output:

Importing librairies...
No module named 'logic'
Collecting einops
  Downloading einops-0.6.0-py3-none-any.whl (41 kB)
     ---------------------------------------- 41.6/41.6 kB 2.0 MB/s eta 0:00:00
Installing collected packages: einops
Successfully installed einops-0.6.0

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python-real.exe -m pip install --upgrade pip
Collecting monai==0.7.0
  Using cached monai-0.7.0-202109240007-py3-none-any.whl (650 kB)
Requirement already satisfied: torch>=1.5 in c:\users\andra\appdata\local\na-mic\slicer 5.2.1\lib\python\lib\site-packages (from monai==0.7.0) (1.13.1+cu117)
Requirement already satisfied: numpy>=1.17 in c:\users\andra\appdata\local\na-mic\slicer 5.2.1\lib\python\lib\site-packages (from monai==0.7.0) (1.23.4)
Requirement already satisfied: typing-extensions in c:\users\andra\appdata\local\na-mic\slicer 5.2.1\lib\python\lib\site-packages (from torch>=1.5->monai==0.7.0) (4.4.0)
Installing collected packages: monai
Successfully installed monai-0.7.0

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python-real.exe -m pip install --upgrade pip
Collecting itk
  Downloading itk-5.3.0-cp39-cp39-win_amd64.whl (8.3 kB)
Collecting itk-segmentation==5.3.0
  Downloading itk_segmentation-5.3.0-cp39-cp39-win_amd64.whl (5.1 MB)
     ---------------------------------------- 5.1/5.1 MB 10.1 MB/s eta 0:00:00
Collecting itk-io==5.3.0
  Downloading itk_io-5.3.0-cp39-cp39-win_amd64.whl (8.6 MB)
     ---------------------------------------- 8.6/8.6 MB 12.5 MB/s eta 0:00:00
Collecting itk-core==5.3.0
  Downloading itk_core-5.3.0-cp39-cp39-win_amd64.whl (36.4 MB)
     ---------------------------------------- 36.4/36.4 MB 7.0 MB/s eta 0:00:00
Collecting itk-registration==5.3.0
  Downloading itk_registration-5.3.0-cp39-cp39-win_amd64.whl (9.4 MB)
     ---------------------------------------- 9.4/9.4 MB 10.9 MB/s eta 0:00:00
Collecting itk-numerics==5.3.0
  Downloading itk_numerics-5.3.0-cp39-cp39-win_amd64.whl (20.0 MB)
     ---------------------------------------- 20.0/20.0 MB 8.3 MB/s eta 0:00:00
Collecting itk-filtering==5.3.0
  Downloading itk_filtering-5.3.0-cp39-cp39-win_amd64.whl (23.8 MB)
     ---------------------------------------- 23.8/23.8 MB 7.4 MB/s eta 0:00:00
Requirement already satisfied: numpy in c:\users\andra\appdata\local\na-mic\slicer 5.2.1\lib\python\lib\site-packages (from itk) (1.23.4)
Installing collected packages: itk-core, itk-numerics, itk-io, itk-filtering, itk-segmentation, itk-registration, itk
Successfully installed itk-5.3.0 itk-core-5.3.0 itk-filtering-5.3.0 itk-io-5.3.0 itk-numerics-5.3.0 itk-registration-5.3.0 itk-segmentation-5.3.0

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python-real.exe -m pip install --upgrade pip
Collecting connected-components-3d==3.9.1
  Downloading connected_components_3d-3.9.1-cp39-cp39-win_amd64.whl (329 kB)
     -------------------------------------- 329.8/329.8 kB 6.8 MB/s eta 0:00:00
Requirement already satisfied: numpy in c:\users\andra\appdata\local\na-mic\slicer 5.2.1\lib\python\lib\site-packages (from connected-components-3d==3.9.1) (1.23.4)
Installing collected packages: connected-components-3d
Successfully installed connected-components-3d-3.9.1

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python-real.exe -m pip install --upgrade pip
Starting
{'input': 'C:/Users/andra/OneDrive/Documents/PostDentalSurgery.nrrd', 'dir_models': 'C:/tmp/20221226-CMF-Seg', 'high_def': False, 'skul_structure': ['MAND', 'MAX', 'CB', 'CV', 'UAW', 'SKIN', 'CBMASK', 'MANDMASK', 'MAXMASK'], 'merge': ['MERGE'], 'gen_vtk': False, 'save_in_folder': False, 'output_dir': 'C:/Users/andra/OneDrive/Documents/PostDentalSurgery.nrrd', 'precision': 0.5, 'vtk_smooth': 5, 'prediction_ID': 'Pred', 'nbr_GPU_worker': 1, 'nbr_CPU_worker': 1, 'temp_fold': 'C:/Users/andra/OneDrive/Documents\\Slicer_temp_AMASSS', 'merging_order': ['SKIN', 'CV', 'UAW', 'CB', 'MAX', 'MAND', 'CAN', 'RC', 'CBMASK', 'MANDMASK', 'MAXMASK'], 'isSegmentInput': False}
Start
Loading models from C:/tmp/20221226-CMF-Seg
Available models: {'CBMASK': 'C:\\tmp\\20221226-CMF-Seg\\seg_Mask_CB_model.pth', 'MANDMASK': 'C:\\tmp\\20221226-CMF-Seg\\seg_Mask_MAND_model.pth', 'MAXMASK': 'C:\\tmp\\20221226-CMF-Seg\\seg_Mask_MAX_model.pth'}
{'CBMASK': 'C:\\tmp\\20221226-CMF-Seg\\seg_Mask_CB_model.pth', 'MANDMASK': 'C:\\tmp\\20221226-CMF-Seg\\seg_Mask_MAND_model.pth', 'MAXMASK': 'C:\\tmp\\20221226-CMF-Seg\\seg_Mask_MAX_model.pth'}
Loading data from C:/Users/andra/OneDrive/Documents/PostDentalSurgery.nrrd
Importing librairies...
No module named 'logic'
Done in 4.93 seconds
```

**Comment by lumax90** [comment]
My folder where the test file was located had special characters in its name. Fixed the folder name then I ran the Slicer as administrator and the script worked. Now i am getting cuda error. I'm still trying to fix it.

**Comment by lucanchling** [comment]
Hi @lassoan, have you tried using the `Folder as Input` option and choosing the right folder just to make sure that the issue only occurs with a node as input?
And also, you've only downloaded the mask models but selected the other segmentation to be done. You have to DL and extract all the different models (masks and AMASSS models) from there: https://github.com/lucanchling/AMASSS_CBCT/releases/tag/v1.0.2
