### ISSUE TITLE
libraries for slicer automated dental tools

### ISSUE THREAD

**Issue by Adriangazelle** [DCBIA-OrthoLab/SlicerAutomatedDentalTools#81]
Hello, 

I have installed Window 11, 3D Slicer 5.6.1 and the most recent version of the slicer automated dental tools extension.
I tried to use AMASSS.
After Run prediction I get the following message.

![image](https://github.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools/assets/160432587/60c88580-9846-4f93-b716-6b909b03c81c)

After clicking on the yes button, the python console shows:

ERROR: Could not find a version that satisfies the requirement torch==cu118 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0)
ERROR: No matching distribution found for torch==cu118
Traceback (most recent call last):
  File "C:/Users/Gebruiker/AppData/Local/slicer.org/Slicer 5.6.1/slicer.org/Extensions-32438/SlicerAutomatedDentalTools/lib/Slicer-5.6/qt-scripted-modules/AMASSS.py", line 684, in onPredictButton
    libs_installation = install_function(list_libs)
  File "C:/Users/Gebruiker/AppData/Local/slicer.org/Slicer 5.6.1/slicer.org/Extensions-32438/SlicerAutomatedDentalTools/lib/Slicer-5.6/qt-scripted-modules/AMASSS.py", line 81, in install_function
    pip_install(lib_version)
  File "C:\Users\Gebruiker\AppData\Local\slicer.org\Slicer 5.6.1\bin\Python\slicer\util.py", line 3887, in pip_install
    _executePythonModule("pip", args)
  File "C:\Users\Gebruiker\AppData\Local\slicer.org\Slicer 5.6.1\bin\Python\slicer\util.py", line 3848, in _executePythonModule
    logProcessOutput(proc)
  File "C:\Users\Gebruiker\AppData\Local\slicer.org\Slicer 5.6.1\bin\Python\slicer\util.py", line 3814, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['C:/Users/Gebruiker/AppData/Local/slicer.org/Slicer 5.6.1/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', 'torch==cu118']' returned non-zero exit status 1.

How can I make changes to the libraries?

Adrian

**Comment by Jeanneclre** [comment]
Hello @Adriangazelle 
Thank you for your input. Indeed, something wasn't done properly for the installation of torch.
It should be fixed after the pull request is merged. 
Please tell us if you have any other issue :)

Jeanne

**Comment by Adriangazelle** [comment]
Today I reïnstalled slicer 5.6.1 and Slicer automated dental tools.
In AMASSS, after run prediction:

Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Local\slicer.org\Slicer 5.6.1\lib\Python\Lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 35, in __init__
    parsed = _parse_requirement(requirement_string)
  File "C:\Users\Gebruiker\AppData\Local\slicer.org\Slicer 5.6.1\lib\Python\Lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "C:\Users\Gebruiker\AppData\Local\slicer.org\Slicer 5.6.1\lib\Python\Lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "C:\Users\Gebruiker\AppData\Local\slicer.org\Slicer 5.6.1\lib\Python\Lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 126, in _parse_requirement_details
    marker = _parse_requirement_marker(
  File "C:\Users\Gebruiker\AppData\Local\slicer.org\Slicer 5.6.1\lib\Python\Lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 147, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "C:\Users\Gebruiker\AppData\Local\slicer.org\Slicer 5.6.1\lib\Python\Lib\site-packages\pkg_resources\_vendor\packaging\_tokenizer.py", line 165, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
    torch, torchvision, torchaudio
         ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/Gebruiker/AppData/Local/slicer.org/Slicer 5.6.1/slicer.org/Extensions-32438/SlicerAutomatedDentalTools/lib/Slicer-5.6/qt-scripted-modules/AMASSS.py", line 704, in onPredictButton
    libs_installation = install_function(list_libs,platform.system())
  File "C:/Users/Gebruiker/AppData/Local/slicer.org/Slicer 5.6.1/slicer.org/Extensions-32438/SlicerAutomatedDentalTools/lib/Slicer-5.6/qt-scripted-modules/AMASSS.py", line 51, in install_function
    if not check_lib_installed(lib, version):
  File "C:/Users/Gebruiker/AppData/Local/slicer.org/Slicer 5.6.1/slicer.org/Extensions-32438/SlicerAutomatedDentalTools/lib/Slicer-5.6/qt-scripted-modules/AMASSS.py", line 31, in check_lib_installed
    installed_version = pkg_resources.get_distribution(lib_name).version
  File "C:\Users\Gebruiker\AppData\Local\slicer.org\Slicer 5.6.1\lib\Python\Lib\site-packages\pkg_resources\__init__.py", line 526, in get_distribution
    dist = Requirement.parse(dist)
  File "C:\Users\Gebruiker\AppData\Local\slicer.org\Slicer 5.6.1\lib\Python\Lib\site-packages\pkg_resources\__init__.py", line 3215, in parse
    (req,) = parse_requirements(s)
  File "C:\Users\Gebruiker\AppData\Local\slicer.org\Slicer 5.6.1\lib\Python\Lib\site-packages\pkg_resources\__init__.py", line 3174, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "C:\Users\Gebruiker\AppData\Local\slicer.org\Slicer 5.6.1\lib\Python\Lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
    torch, torchvision, torchaudio
         ^

I am sorry, it doesn't work on my pc.

Adrian
