### ISSUE TITLE
ALI doesn't install

### ISSUE THREAD

**Issue by juangmagic** [DCBIA-OrthoLab/SlicerAutomatedDentalTools#94]
Greetings,

I hope this message finds you well. I'm currently utilizing version 5.6.1 of Slicer, and I've recently installed the latest Automated Dental Tools extension. However, I've noticed that the ALI panel isn't appearing in the Slicer menu as expected. It seems that it may not have installed automatically. 

Best regards, Juan
![Captura de pantalla 2024-04-05 175522](https://github.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools/assets/60279092/34ac0d33-b716-48ba-87e9-7bbeeff576a4)

**Comment by juangmagic** [comment]
It seems like conda or other dependencies are not being installed: 
This is the error shown in the python console:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\JFran\AppData\Local\slicer.org\Slicer 5.6.2\lib\Python\Lib\imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:/Users/JFran/AppData/Local/slicer.org/Slicer 5.6.2/slicer.org/Extensions-32448/SlicerAutomatedDentalTools/lib/Slicer-5.6/qt-scripted-modules/ALI.py", line 17, in <module>
    from CondaSetUp import CondaSetUpCall,CondaSetUpCallWsl
ModuleNotFoundError: No module named 'CondaSetUp'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\JFran\AppData\Local\slicer.org\Slicer 5.6.2\lib\Python\Lib\imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:/Users/JFran/AppData/Local/slicer.org/Slicer 5.6.2/slicer.org/Extensions-32448/SlicerDentalModelSeg/lib/Slicer-5.6/qt-scripted-modules/CrownSegmentation.py", line 10, in <module>
    from CondaSetUp import  CondaSetUpCall,CondaSetUpCallWsl
ModuleNotFoundError: No module named 'CondaSetUp'
[Qt] loadSourceAsModule - Failed to load file "C:/Users/JFran/AppData/Local/slicer.org/Slicer 5.6.2/slicer.org/Extensions-32448/SlicerAutomatedDentalTools/lib/Slicer-5.6/qt-scripted-modules/ALI.py"  as module "ALI" !
[Qt] Fail to instantiate module  "ALI"
[Qt] loadSourceAsModule - Failed to load file "C:/Users/JFran/AppData/Local/slicer.org/Slicer 5.6.2/slicer.org/Extensions-32448/SlicerDentalModelSeg/lib/Slicer-5.6/qt-scripted-modules/CrownSegmentation.py"  as module "CrownSegmentation" !
[Qt] Fail to instantiate module  "CrownSegmentation"
[Qt] The following modules failed to be instantiated:
[Qt]    ALI
[Qt]    CrownSegmentation

**Comment by allemangD** [comment]
This may be fixed in the recent changes pushed to the extension index yesterday. Could you try un-installing and re-installing both `SlicerAutomatedDentalTools` and `SlicerDentalModelSeg`?

You could also try running the extension on the current Preview release of Slicer

**Comment by GaelleLeroux** [comment]
Yes, this should be corrected in the recent changes pushed. We've created a new extension 'SlicerConda' which is only available on the Preview version of Slicer. This extension is used to run our extension on a Windows system. Because of the import, it created an error in version 5.6 of Slicer. We've fixed this problem in Slicer 5.6 by removing the import at the beginning of our code, so you can now use them again on Linux.

To resume, if you're on Windows and want to use ALI and SlicerDentalModelSeg, you'll need to install the Preview version of Slicer where SlicerConda is available. Otherwise, you'll see them, but they won't work.
If you're on a Linux system, you can install Slicer 5.6 or the Preview version of Slicer to use them.

Let us know if you have any problems :)

**Comment by cmfsx** [comment]
Hi 

Thank you for the wonderful work. 
ALI not working for me as well.  All others installs well but the issue come with 

ERROR: Could not find a version that satisfies the requirement pytorch3d (from versions: none)
ERROR: No matching distribution found for pytorch3d

I have tried several versions of 3D Slicer preview release on windows 11. It fails. AMASS works well. 

Can I have some insight on how to fix this ? 

Thank you
